# rustfmt.toml
# Keep this aligned with rust-toolchain.toml and CI.

unstable_features = true

edition = "2021"
style_edition = "2021"

max_width = 100
newline_style = "Unix"

# Match formatting
match_block_trailing_comma = true

# Comment formatting
wrap_comments = true
comment_width = 100
normalize_comments = true