//! Panic/oops formatter — register dump, frame-pointer stack backtrace,
//! and best-effort symbol resolution.
//!
//! # Usage
//!
//! `oops` is called from the `#[panic_handler]` in `src/kernel_main.rs`
//! when the kernel is built with `--features debug` (which also implies
//! `debug_stub` and `trace` via Cargo feature dependencies).
//!
//! The panic handler emits a canonical `KERNEL PANIC at file:line:col`
//! header unconditionally; `oops` then adds the register dump, backtrace,
//! and trace drain on top of that.
//!
//! # Register dump
//!
//! When a panic originates from a trap handler, pass the `TrapFrame` pointer
//! for a full register dump. For bare Rust panics the current `rsp`/`rbp`
//! (x86_64) or `sp`/`fp` (RISC-V) are snapshotted via inline asm.
//!
//! # Backtrace
//!
//! Requires frame pointers. Add to every `[profile.*]` section in
//! `Cargo.toml`:
//! ```toml
//! force-frame-pointers = true
//! ```
//!
//! # Symbol resolution
//!
//! A sorted `(address, name)` table is embedded at build time by `build.rs`
//! (generated from `llvm-nm --numeric-sort` on the kernel ELF). At runtime
//! `resolve_symbol` binary-searches the table for the nearest symbol.

use core::sync::atomic::{AtomicBool, Ordering};

/// Guard against re-entrant panics while printing the oops message.
static IN_OOPS: AtomicBool = AtomicBool::new(false);

// ---------------------------------------------------------------------------
// Symbol table (generated by build.rs into $OUT_DIR/symbols.rs)
// ---------------------------------------------------------------------------

/// Fallback empty table so the crate compiles without a generated symbols file.
#[cfg(not(has_symbol_table))]
static SYMBOLS: &[(usize, &str)] = &[];

#[cfg(has_symbol_table)]
include!(concat!(env!("OUT_DIR"), "/symbols.rs"));

/// Resolve a virtual address to the nearest kernel symbol name.
///
/// Returns `"<unknown>"` when the table is empty or the address precedes all
/// known symbols.
pub fn resolve_symbol(addr: usize) -> &'static str {
    if SYMBOLS.is_empty() {
        return "<unknown>";
    }
    match SYMBOLS.binary_search_by_key(&addr, |&(a, _)| a) {
        Ok(i)  => SYMBOLS[i].1,
        Err(0) => "<unknown>",
        Err(i) => SYMBOLS[i - 1].1,
    }
}

// ---------------------------------------------------------------------------
// Frame-pointer backtrace
// ---------------------------------------------------------------------------

/// Maximum call-stack depth to unwind before giving up.
const MAX_FRAMES: usize = 32;

/// Walk the frame-pointer chain starting at `fp`, printing each return
/// address and its resolved symbol to the kernel serial console.
///
/// # Safety
/// `fp` must be a valid, aligned stack frame pointer or `0`.
pub unsafe fn backtrace_from(fp: usize) {
    crate::serial_println!("--- backtrace ---");
    let mut frame = fp;
    for depth in 0..MAX_FRAMES {
        if frame == 0 || frame & 0x7 != 0 {
            break;
        }
        // Standard ABI frame layout (x86_64 and RISC-V with frame pointers):
        //   [fp + 0]  = saved fp of caller
        //   [fp + 8]  = return address
        let ret_addr = *(frame as *const usize).add(1);
        if ret_addr == 0 {
            break;
        }
        let sym = resolve_symbol(ret_addr);
        crate::serial_println!("  #{depth:2}: {ret_addr:#018x}  {sym}");
        frame = *(frame as *const usize);
    }
    crate::serial_println!("--- end backtrace ---");
}

/// Capture the current frame pointer via inline asm and call [`backtrace_from`].
pub fn backtrace() {
    let fp: usize;
    #[cfg(target_arch = "x86_64")]
    unsafe {
        core::arch::asm!("mov {}, rbp", out(reg) fp);
    }
    #[cfg(target_arch = "riscv64")]
    unsafe {
        // s0 / x8 is the frame pointer register on RISC-V.
        core::arch::asm!("mv {}, s0", out(reg) fp);
    }
    #[cfg(not(any(target_arch = "x86_64", target_arch = "riscv64")))]
    { fp = 0; }
    unsafe { backtrace_from(fp); }
}

// ---------------------------------------------------------------------------
// Register dump helpers
// ---------------------------------------------------------------------------

/// Print all general-purpose registers for an x86_64 trap frame.
///
/// Call from your x86_64 trap handler, passing a pointer to the saved
/// register area on the kernel stack.
#[cfg(target_arch = "x86_64")]
pub fn dump_regs_x86_64(regs: &crate::arch::x86_64::TrapFrame) {
    crate::serial_println!("--- registers (x86_64) ---");
    crate::serial_println!("  rax={:#018x}  rbx={:#018x}  rcx={:#018x}",
        regs.rax, regs.rbx, regs.rcx);
    crate::serial_println!("  rdx={:#018x}  rsi={:#018x}  rdi={:#018x}",
        regs.rdx, regs.rsi, regs.rdi);
    crate::serial_println!("  r8 ={:#018x}  r9 ={:#018x}  r10={:#018x}",
        regs.r8,  regs.r9,  regs.r10);
    crate::serial_println!("  r11={:#018x}  r12={:#018x}  r13={:#018x}",
        regs.r11, regs.r12, regs.r13);
    crate::serial_println!("  r14={:#018x}  r15={:#018x}  rbp={:#018x}",
        regs.r14, regs.r15, regs.rbp);
    crate::serial_println!("  rip={:#018x}  rsp={:#018x}  rflags={:#018x}",
        regs.rip, regs.rsp, regs.rflags);
    crate::serial_println!("--- end registers ---");
}

/// Print all general-purpose registers for a RISC-V trap frame.
#[cfg(target_arch = "riscv64")]
pub fn dump_regs_riscv(regs: &crate::arch::riscv64::TrapFrame) {
    crate::serial_println!("--- registers (riscv64) ---");
    crate::serial_println!("  ra ={:#018x}  sp ={:#018x}  gp ={:#018x}",
        regs.ra, regs.sp, regs.gp);
    crate::serial_println!("  tp ={:#018x}  t0 ={:#018x}  t1 ={:#018x}",
        regs.tp, regs.t0, regs.t1);
    crate::serial_println!("  t2 ={:#018x}  s0 ={:#018x}  s1 ={:#018x}",
        regs.t2, regs.s0, regs.s1);
    crate::serial_println!("  a0 ={:#018x}  a1 ={:#018x}  a2 ={:#018x}",
        regs.a0, regs.a1, regs.a2);
    crate::serial_println!("  a3 ={:#018x}  a4 ={:#018x}  a5 ={:#018x}",
        regs.a3, regs.a4, regs.a5);
    crate::serial_println!("  a6 ={:#018x}  a7 ={:#018x}",
        regs.a6, regs.a7);
    crate::serial_println!("  sepc={:#018x}  scause={:#018x}  stval={:#018x}",
        regs.sepc, regs.scause, regs.stval);
    crate::serial_println!("--- end registers ---");
}

// ---------------------------------------------------------------------------
// Top-level oops entry point
// ---------------------------------------------------------------------------

/// Enrich a panic with a register dump and backtrace.
///
/// The `#[panic_handler]` in `src/kernel_main.rs` already emits a
/// `KERNEL PANIC at file:line:col: message` header before calling this;
/// `oops` adds the register dump, backtrace, and trace drain on top.
///
/// Only called when built with `--features debug` (which implies both
/// `debug_stub` and `trace` via Cargo feature dependencies).
///
/// ```rust
/// #[panic_handler]
/// fn panic(info: &core::panic::PanicInfo) -> ! {
///     // emit canonical header with location...
///     #[cfg(feature = "debug")]
///     crate::debug::oops::oops(info.message().as_str().unwrap_or("(no message)"));
///     loop { core::hint::spin_loop(); }
/// }
/// ```
pub fn oops(msg: &str) {
    // Prevent recursive oops storms.
    if IN_OOPS.compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst).is_err() {
        return;
    }
    crate::serial_println!("\n!!! KERNEL OOPS !!!");
    crate::serial_println!("message: {}", msg);
    backtrace();
    // Flush any pending trace events so the last events before the crash
    // are visible on the serial console.
    #[cfg(feature = "trace")]
    crate::debug::trace::drain(|ev| {
        crate::serial_println!(
            "  trace [{:?}] id={} arg={:#x} ticks={}",
            ev.kind, ev.id, ev.arg, ev.ticks
        );
    });
}
